TCL 트랜잭션

SELECT *
    FROM DEPT;
    
DELETE FROM DEPT
WHERE DEPTNO = 10;

======실습
DROP TABLE DEPT_TCL;
CREATE TABLE DEPT_TCL
    AS SELECT *
        FROM DEPT;
        
SELECT *
    FROM DEPT_TCL;
    
INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';
SELECT *
    FROM DEPT_TCL;
    
ROLLBACK;
SELECT *
    FROM DEPT_TCL;  
    
    
=======
--DELETE : 데이터 하나하나 삭제 (테이블 有)
--TRUNCATE : 데이터 모두 삭제 (테이블 有)
--DROP : 테이블 삭제

--DDL : 데이터 정의어 - 객체에 관한 SQL문

===========
12강 연습문제

CREATE TABLE EMP_HW (
    EMPNO  NUMBER(4),
    ENAME  VARCHAR2(10),
    JOB    VARCHAR2(9),
    MGR    NUMBER(4),
    HIREDATE  DATE,
    SAL    NUMBER(7,2),
    COMM   NUMBER(7,2),
    DEPTNO NUMBER(2)
    );

DESC  EMP_HW;

==== 2   
ALTER TABLE EMP_HW
    ADD BIGO VARCHAR2(20);

DESC  EMP_HW;
    
    
====3    
ALTER TABLE EMP_HW
    MODIFY BIGO  VARCHAR2(30);
 
DESC  EMP_HW;


====4
ALTER TABLE EMP_HW
    RENAME COLUMN BIGO TO REMARK;

DESC  EMP_HW;


====5
INSERT INTO EMP_HW 
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL 
  FROM EMP;
  
SELECT * FROM EMP_HW;

====6
DROP TABLE EMP_HW;


===========13강
SELECT * FROM DICT
WHERE TABLE_NAME LIKE '%TAB%';

SELECT * FROM ALL_TABLES
WHERE TABLE_NAME = 'EMP';

SELECT * FROM USER_TABLES
WHERE TABLE_NAME = 'EMP';


=============

