====7강 연습문제====

--1
SELECT DNO, TRUNC(AVG(SAL)) AS AVG_SAL, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL, COUNT(ENAME) AS CNT
FROM EMP
GROUP BY DNO;

--2
SELECT JOB , COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3;

--3
SELECT TO_CHAR(HIREDATE,'YYYY'), DNO, COUNT(ENAME)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'), DNO
ORDER BY TO_CHAR(HIREDATE,'YYYY');


--4
SELECT COUNT(ENAME),
    NVL2(COMM, 'O', 'X') AS EXIST_COMM
    FROM EMP
    GROUP BY NVL2(COMM, 'O', 'X');
    
--5
SELECT DNO, TO_CHAR(HIREDATE, 'YYYY'), COUNT(ENAME), MAX(SAL), SUM(SAL), AVG(SAL)
    FROM EMP
    GROUP BY ROLLUP (DNO, TO_CHAR(HIREDATE, 'YYYY'));
    
=================
8강 JOIN : 테이블 연결

SELECT EMP.EMPNO, EMP.ENAME, DEPT.DNAME, EMP.SAL
    FROM EMP, DEPT
        ORDER BY EMP.EMPNO;
        
SELECT EMP.EMPNO, EMP.ENAME, DEPT.DNAME, EMP.SAL
    FROM EMP, DEPT
    WHERE EMP.DNO = DEPT.DEPTNO
        ORDER BY EMP.EMPNO;
        
SELECT EMP.EMPNO, EMP.ENAME, EMP.SAL, EMP.DNO, DEPT.DEPTNO, DEPT.DNAME
    FROM EMP, DEPT
    WHERE EMP.DNO = DEPT.DEPTNO
        ORDER BY EMP.EMPNO;
        
SELECT E.EMPNO, E.ENAME, E.SAL, E.DNO, D.DEPTNO, D.DNAME
    FROM EMP E , DEPT D   --가명 쓰기
    WHERE E.DNO = D.DEPTNO    --(EQUI JOIN) : 동일 조인
        ORDER BY E.EMPNO;
        
SELECT EMPNO, ENAME, SAL, DEPTNO, DNAME
    FROM EMP INNER JOIN DEPT   --가명 쓰기
        ON EMP.DEPTNO = DEPT.DEPTNO    --(EQUI JOIN) : 동일 조인
        ORDER BY EMP.DEPTNO;
        
SELECT E.EMPNO, E.ENAME, E.SAL, E.DNO, D.DEPTNO, D.DNAME
    FROM EMP E , DEPT D   --가명 쓰기
    WHERE E.DNO = D.DEPTNO    --(EQUI JOIN/
        ORDER BY E.DNO;       -- LEFT/RIGHT/FULL OUTER JOIN
        
SELECT *
FROM DEPT;

SELECT *
FROM EMP, DEPT
ORDER BY EMPNO;  

SELECT DISTINCT DNO
    FROM EMP
    ORDER BY DNO;
    
SELECT DISTINCT DEPTNO
    FROM DEPT
    ORDER BY DEPTNO;

SELECT E.DEPTNO, D.DEPTNO
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO;
    
SELECT DISTINCT EMP.DEPTNO, DEPT.DEPTNO   --중복없이
    FROM EMP, DEPT
    WHERE EMP.DEPTNO(+) = DEPT.DEPTNO   --RIGHT OUTER JOIN
    ORDER BY EMP.DEPTNO;
    
SELECT DISTINCT EMP.DEPTNO, DEPT.DEPTNO   --중복없이
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO(+)  --LEFT OUTER JOIN
    ORDER BY EMP.DEPTNO;
    
SELECT DISTINCT DEPTNO
    FROM EMP;

INSERT INTO EMP VALUES
(7001,'SMITH','CLERK',    7902,to_date('17-12-1980','dd-mm-yyyy'),800,NULL,70);
INSERT INTO EMP VALUES
(7002,'SMITH','CLERK',    7902,to_date('17-12-1980','dd-mm-yyyy'),800,NULL,60);
INSERT INTO EMP VALUES
(7000,'SMITH','CLERK',    7902,to_date('17-12-1980','dd-mm-yyyy'),800,NULL,50);
    
SELECT DISTINCT EMP.DEPTNO, DEPT.DEPTNO   --중복없이
    FROM EMP LEFT OUTER JOIN DEPT   --왼쪽 기준!
        ON EMP.DEPTNO = DEPT.DEPTNO
    ORDER BY EMP.DEPTNO;
    
    
SELECT DISTINCT EMP.DEPTNO, DEPT.DEPTNO   --중복없이
    FROM EMP RIGHT OUTER JOIN DEPT   --오른쪽 기준!
        ON EMP.DEPTNO = DEPT.DEPTNO
    ORDER BY EMP.DEPTNO;    
    
    
SELECT DISTINCT EMP.DEPTNO, DEPT.DEPTNO   --중복없이
    FROM EMP FULL OUTER JOIN DEPT   --양쪽 다
        ON EMP.DEPTNO = DEPT.DEPTNO
    ORDER BY EMP.DEPTNO;